# Generated by Django 4.0.1 on 2022-02-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_level_accountlevel_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountLevel',
            new_name='Level',
        ),
    ]
