# Generated by Django 4.0.1 on 2022-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_accountlevel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='point',
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
