# Generated by Django 4.0.1 on 2022-02-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_image_accounticons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounticons',
            options={'verbose_name': 'Icon'},
        ),
        migrations.RemoveField(
            model_name='accounticons',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accounticons'),
        ),
    ]
