# Generated by Django 4.0.1 on 2022-02-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accounticons_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounticons',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
