# Generated by Django 4.0.1 on 2022-02-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_level_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounticons',
            old_name='uploaded',
            new_name='uploaded_at',
        ),
    ]
