# Generated by Django 4.0.1 on 2022-02-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accounticons_name'),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='challengecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ChallengeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChallengeReq_accepted_by', to='account.account')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChallengeReq_account', to='account.account')),
            ],
        ),
    ]
