# Generated by Django 4.0.1 on 2022-02-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_rename_question_question_text_remove_question_status_and_more'),
        ('challenge', '0003_alter_challengerequest_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecategory',
            name='question_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChallengeCategory_question_4', to='question.question'),
        ),
    ]
