# Generated by Django 4.0.1 on 2022-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challengecategory_question_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
