# Generated by Django 4.0.1 on 2022-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challenge_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='wins_account_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='wins_account_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
