# Generated by Django 4.0.1 on 2022-02-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_accounticon_alter_account_icon_delete_accounticons'),
        ('challenge', '0006_challenge_wins_account_1_challenge_wins_account_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('win', 'Win'), ('equal', 'Equal'), ('loss', 'Loss')], max_length=5)),
                ('coin', models.CharField(max_length=50)),
                ('xp', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_result_account', to='account.account')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_result_CHALLENGE', to='challenge.challenge')),
            ],
        ),
    ]
