# Generated by Django 4.0.1 on 2022-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_challengeresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresult',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengeresult',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
