# Generated by Django 4.0.1 on 2022-02-24 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_alter_challengeresult_coin_alter_challengeresult_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
